name: Update gonyyi.a link pages

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 2.7
        architecture: x64      
    - name: Update the code
      run: |-
        msg=$(git log --format=%B -n 1 ${{ github.event.after }})
        #msg="${{ github.event.head_commit.message }}" 
        python build.py $msg
    - name: Commit and push if changed
      run: |-
        git config --global user.email "autoupdate@gonyyi.com"
        git config --global user.name "Auto-update"
        git diff
        git add -A
        git commit -m "Updated link pages" || exit 0
        git push
